process-analytics/bonita-day-demo-2023

src/process-monitoring.ts
src/radio-buttons.ts
src/style.css

Animate the happy path.
The code is taken from https://github.com/process-analytics/icpm-demo-2022/blob/v1.0.0/src/happy-path.js and ported to TypeScript.
I see a glitch on an edge while displaying the happy path (both with Chrome and Firefox on Ubuntu 20.04).
I don't see it in the original demo.
https://user-images.githubusercontent.com/27200110/224375012-cbe378a2-fe9b-4db5-ae8f-d93566637da7.mp4

feat: introduce the "process monitoring" use case

---

src/case-monitoring.ts
src/use-case-management.ts

Introduce class to start reducing code coupling
- tippy support
- sub-use case by process
there is still much to do. The code will be refactored again soon.

refactor(case-monitoring): split the code into classes

---

src/case-monitoring-data.ts
src/case-monitoring.ts
src/diagram.ts
src/use-case-management.ts

Also rename the remaining "secondary" wording to "sub-process".

refactor: better encapsulate MainProcessCaseMonitoring

---

src/case-monitoring.ts
src/case-monitoring/supplier.ts
src/style.css

- add popover to the chatgpt answer
- improve popover design
- fix the bug that made the popover disappears on click

feat(supplier): add generated email popover

---

src/case-monitoring/main-process.ts
src/case-monitoring/sub-process.ts
src/use-case-management.ts

Split the code of the main process and the sub process (reduce file size, split responsibilities).

refactor: extract and move the "case-monitoring" code

---

package-lock.json
package.json
src/case-monitoring/supplier.ts

Highlight the first sub-path when starting the process (from start to )
Then, highlight the  "review and adapt email" activity and decrease the opacity of the first sub-path.

feat(case-monitoring): progressively highlight path of supplier

---

src/diagrams/EC-purchase-orders-collapsed.bpmn
src/process-monitoring.ts

closes #8 
Also fix the "supplier contact" pool name
the glitch disappears after process re-design

fix(process-monitoring): fix glitch in edge animation

---

src/case-monitoring/supplier.ts

class `SupplierProcessTippySupport` does not need to be accessed from outside anymore

refactor(supplier): simplify popover content management

---

src/style.css

fix(supplier): fix content outside popover

---

src/case-monitoring/abstract.ts
src/case-monitoring/main-process.ts
src/case-monitoring/sub-process.ts

fix(case-monitoring): no overlay on the running task of the sub-process

---

src/process-monitoring.ts

Demonstrate that the external process/system sending the message slows the execution down.

feat(happy-path): activate the "catch msg" flow at last

---

src/process-monitoring.ts

feat(process-monitoring): replace overlay with popover

---

src/process-monitoring.ts
src/use-case-management.ts

This is now consistent with the rest of the code.
covers #73 
This will be easier to implement #73 with this change. The process-monitoring code is self contained in the class which acts like a "component" and it can handle it lifecycle by itself.

refactor(process-monitoring): put the whole code in a class

---

src/case-monitoring/data-recommendation.ts
src/case-monitoring/main-process.ts
src/case-monitoring/sub-process.ts
src/style.css

main-process:
- improve the wording of the description and the table (to match the referenced action)
- improve the table layout
- refactor: improve robustness of the "Act" buttons. Do not generate the button ids from the element title. This broke the retrieval of the button when the title changed.
sub-process:
- Wording: from "Resource" to "Actor"
- Use real first names
- Display a workload percentage instead of the availability status (all actors are available)
- Adjust the text position in the table
closes #39 
**Main process**
before | after
----- | ------
**sub-process**
before | after
----- | ------

feat(case-monitoring): improve the content of the popovers

---

src/case-monitoring/supplier-utils.ts
src/case-monitoring/supplier.ts

feat(supplier): add gpt answers

---

src/case-monitoring/abstract.ts
src/case-monitoring/main-process.ts
src/case-monitoring/supplier.ts

feat(supplier): pause/resume main process

---

src/process-monitoring.ts

This simplifies the change of the value (no need to search inside the code).

refactor(process-monitoring): add "popover show delay" constant

---

src/case-monitoring/supplier-utils.ts
src/case-monitoring/supplier.ts

Remove hard coded configuration and tight implementation between several classes (SupplierContact, ProcessExecutor, SupplierTippySupport). For instance, the way the process is resumed is now configured in the execution steps and enrich by the ProcessExecutor.
Event handling and popovers creation has also been simplified by removing duplication. Simplify HTML code generation in `getEmailReviewContent`.

refactor(case-monitoring): simplify popovers in "Supplier Contact"

---

src/case-monitoring/supplier-utils.ts

Display the counter on the edge of the "regenerate email" loop.
fixes #48 
https://user-images.githubusercontent.com/27200110/228038412-0c8d9c1f-5bc6-44d1-9bdd-72d1815f7569.mp4

feat(supplier): add overlay on edge to count the number of visits

---

package-lock.json
package.json
src/case-monitoring/sub-process.ts

feat(subprocess): display notification when clicking on "assign" button

---

src/case-monitoring/sub-process.ts
src/case-monitoring/supplier-utils.ts
src/utils/shared.ts

Also extract the notification code to shared utils
closes #47

feat(supplier): display notification at the end of the execution

---

README.md

docs: explain the content of the demo in the README

---

src/case-monitoring/abstract.ts
src/case-monitoring/main-process.ts
src/case-monitoring/sub-process.ts
src/style.css

closes #56 
- Remove the "?" overlay
- Set the color of the late-running activities to #f9b842 as proposed in #56
- Homogenize the colors of the late-running activities
- Update the colors in the sub-process to be harmonized with the new #f9b842 color.  Variations of blue are used, similarly to the colors used in the supplier process.

feat(case-monitoring): improve design activities

---

index.html
src/breadcrumb.ts
src/diagram.ts

refactor: rename 'secondary' view into 'sub-process'

---

README.md

Add emojis that were missing in the title of some paragraphs.

docs: add emoji to paragraphs in the README

---

package-lock.json
package.json
src/case-monitoring/data-case.ts
src/process-monitoring.ts

The package has been renamed.
Covers https://github.com/process-analytics/bpmn-visualization-addons/issues/310

chore(deps): switch to @process-analytics/bpmn-visualization-addons
