src/case-monitoring.ts
src/radio-buttons.ts

Also blur edge incoming to the pending gateway because they relate to a path that is already executed.
**Note**: from Firefox on Ubuntu 20.04
_Executed path before this PR_
https://user-images.githubusercontent.com/27200110/224386621-a3c71347-b9b6-40e4-b1d3-dcb889f1ab7f.mp4

feat: hide "case monitoring" data when switching to another use case

---

.github/actions/build/action.yml
.github/workflows/build.yml
.github/workflows/deploy-pr-preview.yml
README.md
package.json
src/bpmn-elements.ts
src/breadcrumb.ts
src/diagram.ts
src/main.ts
src/radio-buttons.ts

- Do not put type information in the name of the variables (this is useless as we used types)
- Simplify CSS selector to get elements of the breadcrumb
- Share diagram load options for the all diagrams
- Build and workflows
- Use a more convenient name for the npm script that does TS compilation
- Keep a single build demo npm script for simplificty
- Use the `bahmutov/npm-install` action to manage cache and dependencies install
The "build and workflows" improvements will be then contributed back to https://github.com/process-analytics/bpmn-visualization-demo-template: https://github.com/process-analytics/bpmn-visualization-demo-template/pull/7

refactor: simplify some code and build scripts

---

src/bpmn-elements.ts
src/case-monitoring-data.ts
src/case-monitoring.ts
src/diagram.ts
src/process-monitoring.ts
src/style.css
src/use-case-management.ts
src/utils/bpmn-elements.ts
src/utils/paths.ts

When clicking on the "Allocate more resource" button, the sub-process diagram is displayed.
- It's running task is highlighted and the path leading to it is modified as well. This task proposed a popover which opens on hover.
- In the future, the style of some elements of the diagram will be modified when hovering on the row of the popover.
When clicking on the "Contact-Client" button, a window alert is displayed. In the future, it will display the 2nd process of the diagram and it will let interact with it.
This PR introduces refactoring to better encapsulate the logic.
In particular, it provides classes that may be reused outside this demo and served as starting point for experimental features
- BpmnElementsSearcher https://github.com/process-analytics/bpmn-visualization-js/issues/2453 …

feat: add resource allocation interaction (1st step)

---

index.html

A CSS class was present by mistake and capitalized the text of the elements of the diagram and the text in the popover.
process | before | after
----- | ----- | -----
main | ![01_before_main_process_02_cropped](https://user-images.githubusercontent.com/27200110/225030055-5f0d14aa-53d5-4d76-8864-59a95944504e.png) | ![02_after_main_process_02_cropped](https://user-images.githubusercontent.com/27200110/225030066-2ec980e8-b627-4427-ba98-f4bc686862a0.png)
subprocess | ![01_before_sub-process_02_cropped](https://user-images.githubusercontent.com/27200110/225030063-ab5d8e47-4808-4167-8c3e-0bd3066aa9f6.png) | ![02_after_sub-process_02_cropped](https://user-images.githubusercontent.com/27200110/225030071-d024d93a-71de-4d83-8de4-e4f3b69bb69e.png)

fix: do not capitalize the text

---

src/breadcrumb.ts
src/case-monitoring-data.ts
src/case-monitoring.ts
src/diagram.ts
src/main.ts
src/use-case-management.ts

Treat the initialization and loading of the main diagram in the same way as we do for the sub-process diagram.
This involves lazily loading the initialization of the various parts that previously assumed that the main diagram was loaded and thus, that searches always returned elements
The other refactoring of the views mainly concerns the improvement of the naming of functions and variables.
Previously, there was a bug in the case monitoring use case after we displayed the data on the sub-process.
If in the sub-process view, we decided to change the use case (click on a radio button) and we go back to the main view, the diagram was broken. Most shapes strokes and some labels disappeared.
Changing the use case make the stroke reappear but some labels were missing.
**TODO video @assynour …

refactor: do lazy initializations and improve view management

---

src/case-monitoring-data.ts
src/case-monitoring.ts
src/case-monitoring/abstract.ts
src/case-monitoring/supplier.ts
src/diagram.ts
src/use-case-management.ts

In the case monitoring, the listeners on the elements within the popovers were not removed. There were side effects when the popover show again as there were several listeners to do the same thing.
When quitting the sub-process and going back, the popover didn't highlight the activities. This is now fixed by using a more precise CSS selector.
Additional fix: when displaying the sub-process of the case-monitoring and going to the "none" use case, the sub-process still contained the highlight element and its related popover

fix(case-monitoring): remove listeners on popover elements

---

src/case-monitoring/main-process.ts
src/case-monitoring/supplier.ts

- Make sure to abort the execution of the async supplier contact case before hiding data
- Execution is not aborted when going from the **case monitoring** to the **subprocess view** (for resource allocation)

feat(supplier): hide supplier data

---

src/case-monitoring/abstract.ts
src/case-monitoring/main-process.ts
src/case-monitoring/sub-process.ts
src/case-monitoring/supplier.ts
src/use-case-management.ts

Prefer to pass the "tippy support" collaborator for a better separation of concerns instead of making CaseMonitoring aware of how it is instantiated.

refactor: inject "tippy support" collaborator in `CaseMonitoring`

---

src/case-monitoring/main-process.ts
src/case-monitoring/supplier-utils.ts
src/case-monitoring/supplier.ts

Manage the simulation of the execution of the "Supplier Contact" process execution. It lets configure the execution and the highlight of the paths. In the future, interactions with the "Review and adjust email" popover will also be managed.
The interactions are currently simulated by clicking on the elements of the diagram
- "review and adjust email": request new suggestion
- gateway: send email
- abort end event: abort
Also start improving the global asynchronous execution (this is still a work in progress, a lot of things remains to do).
https://user-images.githubusercontent.com/27200110/226629127-2bdffe96-9610-484f-86eb-86276e41f221.mp4
**_without the popover_**
https://user-images.githubusercontent.com/27200110/226629117-d98fade2-d74c-4eba-9a04-ed7ffbefa06c.mp4
**_with the existing …

feat: introduce `ProcessExecutor` for the Supplier Contact process

---

package-lock.json
package.json

- `typescript` from 4.9.5 to 5.0.2
- `vite` from 4.1.4 to 4.2.1
I tested the dev server on my local machine
The "build" GH workflow tests the TS compiler
The surge preview tests the built demo

chore(deps-dev): bump typescript and vite

---

src/case-monitoring/supplier-utils.ts
src/case-monitoring/supplier.ts
src/utils/shared.ts

- on the "email generation" activity: display the popover and change its content
- then, continue the execution
- then, display the popover to decide what to do with the suggested email
- hide the popover when clicking on the buttons
- end case: remove the path highlight only at the end, after having wait, just before hiding the process
closes #64 
https://user-images.githubusercontent.com/27200110/227160375-e9416d52-aedf-4623-bd1a-5a9a95a6dc6e.mp4

feat(supplier): process executor manages popovers

---

src/process-monitoring.ts

closes #43 
Note: delay property of tippy.js works on event trigger https://atomiks.github.io/tippyjs/v6/all-props/#delay. 
In our case we are showing the popover programmatically

feat(process-monitoring): fix content and delay of overlay

---

src/case-monitoring/abstract.ts
src/case-monitoring/main-process.ts
src/case-monitoring/supplier.ts
src/index.ts
src/process-monitoring.ts
src/style.css

"review suggestion"
- layout: display the suggestion first to have the prompt close to the buttons
- make the textarea non-resizable
- add arrow to popover like in all popovers where users can act
"email generation"
- use tippy light theme
- add loading spinner in the 2nd message
Fix tippy theme loading:
- use the tippy 'default' theme by default
- allow to load the tippy 'light' theme
Also includes some refactoring:
- style: use rem instead of px (popover)
- supplier addInfo: simplify options computation
closes #83
https://user-images.githubusercontent.com/27200110/227782423-61a2dce9-ed71-412a-8e03-ef97ebec623e.mp4

feat(case-monitoring): rework the 'Supplier Contact' popovers

---

src/case-monitoring/supplier.ts
src/use-case-selectors.ts

Currently, the "Supplier Contact" process cannot be stopped properly. To avoid side effects, disable the ability to change use cases while it is running.
fixes #58

fix(case-monitoring): disable use-case switch in "Supplier"

---

src/case-monitoring/sub-process.ts
src/case-monitoring/supplier-utils.ts
src/index.ts
src/utils/shared.ts

Introduce a class to hide the 'Notyf' library to the code using the notification. This makes the notification easier to create and remove adherence to an external library at several places in the application.
Don't hard code the condition that triggers the display of notifications in `ProcessExecutor`. `ProcessExecutor` is intended to be as general as possible for a future near reuse outside of this demonstration
Notifications are now made configurable in the `ExecutionStep`.
Change NotificationType from enum to type. There is no need to enumerate the values and TS enum doesn't operate very well with JS code, so let's avoid them when alternatives exist.
Include remarks done in https://github.com/process-analytics/bonita-day-demo-2023/pull/94#pullrequestreview-1360919275

refactor: reorganize notifications

---

src/case-monitoring/sub-process.ts
src/diagram.ts
src/utils/paths.ts

This is possible thanks to a fix available in bpmn-visualization 0.33.1. Previously, the data could only be hidden if the sub-process diagram was already loaded. This forced to leak the internal state and made the code harder to understand.
Also improve the robustness of the PathResolver to handle shapeId that are not available in the diagram. Here, this lets support not loaded diagram.

refactor(case-monitoring): simplify sub-process hide data

---

src/case-monitoring/abstract.ts
src/process-monitoring.ts

This avoids passing the ids of the BPMN elements and/or the name of the CSS classes.
closes #11

refactor: use the new "remove all CSS classes" API

---

package-lock.json
package.json
src/case-monitoring/abstract.ts
src/case-monitoring/supplier-utils.ts

typescript from 5.0.2 to 5.1.3
vite from 4.2.1 to 4.3.9
xo from 0.53.1 to 0.54.2
In production dependencies, allow automatic patch updates.

chore(deps-dev): bump dev dependencies

---

src/case-monitoring/abstract.ts
src/case-monitoring/data-case.ts
src/case-monitoring/main-process.ts
src/case-monitoring/sub-process.ts
src/case-monitoring/supplier-utils.ts
src/case-monitoring/supplier.ts
src/diagram.ts
src/process-monitoring.ts
src/use-case-management.ts
src/utils/bpmn-elements.ts
src/utils/paths.ts

Use `BpmnElementsRegistry` properties in classes when possible instead of storing an instance of
`BpmnVisualization`. This makes the code easier to read and improve the intent.
Pass BpmnElementsRegistry parameter in constructors to simplify the constructor and reduce the dependency to the `BpmnVisualization` type when possible.
closes #52
The change is split into 2 commits to facilitate revert or PR split. I don't think this is needed but who knows 😄

refactor: directly use BpmnElementsRegistry when possible

---

src/case-monitoring/supplier-utils.ts

Simplify code, no need to set all properties to their default values.
closes #41

refactor: use the `resetStyle` method

---

src/case-monitoring/data-case.ts
src/case-monitoring/data-recommendation.ts
src/diagram.ts
src/style.css

CaseMonitoringData: call the `fetch` method that was previously unused and the implementation was duplicated it.
Remove unused
- getRecommendationData function
- DiagramLoadManager.isAlreadyLoad
style.css: remove px unit when value set to 0

refactor: remove unused code
